# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

H_mat_cpp <- function(Y, knots, dt, Sc) {
    .Call(`_cTSLS_H_mat_cpp`, Y, knots, dt, Sc)
}

add_term_cpp2 <- function(yhat, tgrid, cumK, Pk_dt, Kvals, tail_ok) {
    .Call(`_cTSLS_add_term_cpp2`, yhat, tgrid, cumK, Pk_dt, Kvals, tail_ok)
}

